### ISSUE TITLE
Formulas work but then won't reopen

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#145]
Hi
In the attached file  maths.json if you put this

${formula_1}/10^${formula_2}

 into formula_4 it works as expected.

 If you then save, you cannot subsequently load that file. (file attached Math's won't open.json)

[Renderer process error]
Uncaught Error: Error parsing formula "[object Object]" (TypeError: Unexpected type of argument in function pow (expected: number or Complex or BigNumber or Fraction, actual: undefined, index: 1))
at this.sendValue (src/browser/js/app/widgets/maths/formula.js:161:18)
at this.formula.match(/\$\{ (src/browser/js/app/widgets/maths/formula.js:95:13)
at e.value (src/browser/js/app/parser.js:74:30)
at this.getProp (src/browser/js/app/widgets/containers/panel.js:95:19)
at constructor (src/browser/js/app/widgets/containers/tab.js:44:25)
at e.value (src/browser/js/app/parser.js:74:30)
at this.getProp (src/browser/js/app/widgets/containers/panel.js:77:19)
at constructor (src/browser/js/app/widgets/containers/root.js:42:25)
at e.value (src/browser/js/app/parser.js:74:30)
at parser.reset (src/browser/js/app/managers/session.js:41:23)

There's probably a good reason but I can't find it!

Thanks

Mic

[2 json files.zip](https://github.com/jean-emmanuel/open-stage-control/files/1711784/2.json.files.zip)

**Comment by jean-emmanuel** [comment]
Formulas are definitely too strict... it's fixed in git and will be included in next release. Note that next release will introduce a feature that allow writing any widget property as a formula (writing a widget's `value` property this way will give the same result as using a formula), hence deprecating this widget (it will still be around for a while but will end up being removed eventually).

**Comment by jean-emmanuel** [comment]
v0.24.0 is out
