### ISSUE TITLE
broke my app by trying to add clone to modal, though I had done this before

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#245]
[Renderer process error]
Uncaught TypeError: Cannot read property 'n' of undefined
at widgets[i].props.hasOwnProperty (src/browser/js/app/widgets/common/widget.js:315:54)
at Widget.deepCopy (src/browser/js/app/widgets/common/widget.js:246:34)
at this.props[this.parent.getProp (src/browser/js/app/widgets/common/widget.js:69:43)
at constructor (src/browser/js/app/widgets/common/canvas.js:64:25)
at constructor (src/browser/js/app/widgets/sliders/slider.js:9:25)
at constructor (src/browser/js/app/widgets/sliders/fader.js:61:25)
at widgetManager.getWidgetById (src/browser/js/app/parser.js:63:25)
at this.getProp (src/browser/js/app/widgets/containers/panel.js:100:19)
at constructor (src/browser/js/app/widgets/containers/strip.js:39:25)

here is a copy of it... luckily I had just saved a new version cause this one won't open it says parsing error, can you fix it or do I need to start reworking things?

[barryBitwigControlDeviceLayerMixer copy.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1822152/barryBitwigControlDeviceLayerMixer.copy.json.txt)

**Comment by Sebastian-blu** [comment]
lol don't know why that emoji popped in there

**Comment by jean-emmanuel** [comment]
@{parent.value.n} could not resolve, but it shouldn't prevent the session from loading, just fixed it in git.
