### ISSUE TITLE
'Renderer process error' when resizing original+clones

### ISSUE THREAD

**Issue by jamols** [jean-emmanuel/open-stage-control#249]
Editing on Chrome desktop, attempting to resize original panel + clones:

```
[Renderer process error]
Uncaught Error: cannot call methods on resizable prior to initialization; attempted to call method 'destroy'
at g (node_modules/jquery/dist/jquery.slim.min.js:2:0)
at cleanData (src/browser/js/libs/jquery.ui.js:6:0)
at g (node_modules/jquery/dist/jquery.slim.min.js:2:0)
at g (node_modules/jquery/dist/jquery.slim.min.js:2:0)
at cleanData (src/browser/js/libs/jquery.ui.js:6:0)
at unselect (src/browser/js/app/editor/index.js:116:34)
at select (src/browser/js/app/editor/index.js:125:13)
at w.props.height.indexOf (src/browser/js/app/editor/index.js:288:54)
at cleanData (src/browser/js/libs/jquery.ui.js:6:0)
at _destroy (src/browser/js/libs/jquery.ui.js:7:0)
```

**Comment by jean-emmanuel** [comment]
Thanks for the report, just fixed in git !

**Comment by jean-emmanuel** [comment]
-> 0.27.1
