### ISSUE TITLE
syncTargets error after upgrade 0.21 to 0.28.1

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#262]
Hi !
After upgrading for O-S-C 0.21 to 0.28.1, my ardour control session can't be launched.
In the log :
```
App available at http://127.0.0.1:8080 & http://192.168.1.10:8080 & http://192.168.1.125:8080
evalmachine.<anonymous>:16
    var [host, port] = settings.read('syncTargets')[0].split(':')
                                                   ^

TypeError: Cannot read property '0' of undefined
    at evalmachine.<anonymous>:16:52
    at evalmachine.<anonymous>:350:3
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at Object.runInContext (vm.js:108:6)
    at /usr/lib/open-stage-control/resources/app/main/osc.js:144:12
    at Object.<anonymous> (/usr/lib/open-stage-control/resources/app/main/osc.js:151:3)
    at Object.<anonymous> (/usr/lib/open-stage-control/resources/app/main/osc.js:220:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
A JavaScript error occurred in the main process: Uncaught Exception:
TypeError: Cannot read property 'init' of undefined
    at Object.<anonymous> (/usr/lib/open-stage-control/resources/app/main/osc.js:192:17)
    at Object.<anonymous> (/usr/lib/open-stage-control/resources/app/main/osc.js:220:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at start (/usr/lib/open-stage-control/resources/app/main/main.js:21:19)
A JavaScript error occurred in the main process: Uncaught Exception:
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at Object.<anonymous> (/usr/lib/open-stage-control/resources/app/main/server.js:32:8)
    at Object.<anonymous> (/usr/lib/open-stage-control/resources/app/main/server.js:72:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
A JavaScript error occurred in the main process: Uncaught Exception:
Error: bind EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at _handle.lookup (dgram.js:242:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Zeroconf: Service name is already in use on the network
Error: Zeroconf: Service name is already in use on the network
```

**Comment by jean-emmanuel** [comment]
Fixed in ardour-control 3 days ago ;)
https://github.com/jean-emmanuel/ardour-control/commit/6be47b8a616c97457271f50e5dbcdc9ebf2740f3

**Comment by wargreen** [comment]
Cool, fixed thx !
