### ISSUE TITLE
error when selecting a tab

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#283]
If I open the attached file, and then:
``oscsend osc.udp://localhost:8080  /TABS s tab_2``, I get:

```
OSC received:  { address: '/TABS', args: 'tab_2' } From : 127.0.0.1:56200
[Renderer process error]
Uncaught TypeError: Cannot read property 'ctrlKey' of null
    at handleClick (src/browser/js/app/editor/context-menu.js:124:22)
    at dispatchEvent (src/browser/js/app/dom.js:36:16)
    at widgetManager.getWidgetById (src/browser/js/app/remote-control.js:149:24)
    at each (src/browser/js/app/dom.js:74:14)
    at widgetManager.getWidgetById (src/browser/js/app/remote-control.js:148:20)
    at exec (src/browser/js/app/remote-control.js:163:28)
    at receive (src/browser/js/app/osc.js:38:72)
    at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
    at require (src/browser/js/app/ipc/index.js:40:16)
```

Am I doing something incorrect?

Also, I don't understand what is the "OSC (tab selection)" section, and how I can change the values inside...

git version b1e59f2f8f217643f87dfc28b8630a092076a433 (0.30.1)

[2018-05-07_09-39.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1979364/2018-05-07_09-39.json.txt) 

Thank you

**Comment by cyberic99** [comment]
I confirm it is fixed, thanks

**Comment by jean-emmanuel** [comment]
-> 0.30.2 :)
