### ISSUE TITLE
Midi settings / Port

### ISSUE THREAD

**Issue by Manaberry** [jean-emmanuel/open-stage-control#299]
Bonjour Jean-Emmanuel.

Je test un peu Open Stage Control en utilisant le *.exe 64bit windows. 
Pour mon send je met un port a 8000 et 9000 pour osc-port. Ca fonctionne super bien avec Ableton pour les messages OSC, mais pour ce qui est du midi je suis completement pommé.

Dans Midi Router Settings, je sais meme pas ce que ca représente. J'ai un port virtuel mais je ne sais pas comment redirigé Open Stage Control dessus. 

Osc2Midi est CPU killer et de toute facon, j'ai aucun retour midi sur Ableton avec.

Je sais pas trop quoi faire. Je suis sur qu'il y a une solution simple mais impossible de la trouver, la doc j'y pige pas grand chose. Autant j'ai un background sur AngularJS, mais la pour du port/server side je suis a la rue total!

Personne sur VI-Control n'as répondu encore.

Comment faire ?

Merci de m'avoir lu

**Comment by Manaberry** [comment]
J'ai cru comprendre en regardant cette page oui (que j'ai consulté avant de poster).
Le soucis c'est que j'ai aucune idée de comment set le midi. Comme cité plus haut, je suis pommé totalement. 
Désolé vraiment pour ma requete surement débile, mais apres avoir cramé mon cerveau pendant deux jours de suite, toute logique m'as quitté.


When running the app, the -m / --midi switch must be set;
Par exemple ici, j'ai aucune idée de l'endroit ou je dois renseigner les infos. cmd prompt ?

Merci d'avoir répondu ;)

**Comment by jean-emmanuel** [comment]
La documentation fait référence aux options dans leur syntaxe en ligne de commande, mais elles peuvent toutes être réglées depuis l'interface graphique de lancement (quand on double-clique sur l'icone d'o-s-c ou qu'on lance l'appli en ligne de commande mais sans aucune option). Dans cette insterface, les deux tirets précédant le nom des options sont enlevé pour aider la lisibilité, il faut donc remplir le champ "midi" pour regler l'option "--midi" ("-m" est un diminutif valable en ligne de commande). Pour connecter O-S-C à Ableton, suis les étapes suivantes:
- installe les [prérequis](https://osc.ammd.net/extras/midi/#requirements) pour le support MIDI
- lance ableton et active son entrée MIDI si besoin
- lance O-S-C
  - tape `list` dans le champ `midi` et clique sur "start". Un message devrait apparaître en bas de la fenêtre de lancement listant les ports MIDI disponibles
  - redemarre O-S-C (tu peux faire clic-droit>app>relaunch dans la fenêtre de lancement)
  - tape `ableton:1,1` dans le champ `midi` (remplace `1,1` par les numéro des ports d'entrée/sortie d'ableton auxquels tu veux te connecter, ces numéros peuvent changer selon les périphériques connectés à ton ordi) 
  - tu peux maintenant envoyer du midi avec un widget en mettant `midi:ableton` dans l'options `target` et en paramétrant correctement les options `address` et `preArgs` (voir la [doc](https://osc.ammd.net/extras/midi/#supported-midi-messages))

**Comment by Manaberry** [comment]
Genial merci du petit guide. 
J'ai installé Python et rtmidi avec pip.
Avec l'option --midi j'ai une erreur:

```
A JavaScript error occurred in the main process: Uncaught Exception:
Error: spawn python ENOENT
at exports._errnoException (util.js:1024:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
at onErrorNT (internal/child_process.js:374:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jean-emmanuel** [comment]
As-tu bien installé python ?

**Comment by Manaberry** [comment]
OK j'ai réglé le soucis. En gros j'avais une version 36-32 qui n'etait pas reconnu par OSC.
J'ai installé une autre version de Python et j'ai réinstallé rtmidi derriere.

Ca lance sans broncher cette fois ci. Je passe a la suite : >

**Comment by Manaberry** [comment]
OK, j'ai testé avec un keyboard rapidement. Ca fonctionne pour /note. 
La configuration marche niquel. Merci pour tes infos ! C'était surement simple en soit mais j'étais perdu haha! Maintenant c'est clair dans ma tete je vais pouvoir en faire un petit "tuto" Win pour le forum VI.

Merci infiniment encore pour ton aide ! 
Bravo pour ton boulot !

**Comment by jean-emmanuel** [comment]
Super ! N'hésite pas à poster ton tuto ici ;)
Je vais regarder pour la compatibilité python 3.6.

**Comment by Manaberry** [comment]
La version 3.6 fonctionne, mais j'ai installé une version qui s'appelle 36-32 (a mon avis une version 32bits).
https://www.python.org/downloads/release/python-365/

J'ai du installer une version x86 sans faire attention.

Je partagerais le tuto alors ;)

**Comment by jean-emmanuel** [comment]
Je suis tombé sur ton tuto (https://vi-control.net/community/threads/open-stage-control-tutorial-an-alternative-to-lemur-and-touchosc.72643/#post-4245962), super classe l'interface ! J'ajoute ça aux exemples dans la doc...

**Comment by cyberic99** [comment]
Ouah c'est beau! Par contre je trouve ca un peu dangereux de s'appuyer sur imgurl pour les icones... 
En plus ca nécessite d'être online...
il ne vaudrait mieux pas mettre le images en data uri?

**Comment by Manaberry** [comment]
Merci ! 
Pour le moment c'est pas clean comme le souligne Cyberic99. Je dois encore mettre a jour les fichiers dans mon spreadsheet, zipper les images et spécifier que c'est plus simple de mettre le lien des fichiers. 

Le link imgur c'était plus dans l'urgence pour le tuto 🗡 
Je vais l'améliorer au fur et a mesure.

**Comment by cyberic99** [comment]
OK. est ce que tu fourniras le .json de la session, ou pas?

**Comment by Manaberry** [comment]
Oui quand j'aurais tout clean proprement ! Et je fournirais le "MIDI Remote Control Script" pour Ableton live. Mais je dois clean aussi le json de celui ci.

**Comment by cyberic99** [comment]
Super. beau taff en tout cas, surtout coté css je trouve

**Comment by Manaberry** [comment]
Merci ! Je suis content du CSS, j'ai un peu triché pour les toggles des MUTE/UNMUTE. C'est un background rgba et l'opacité change avec la valeur du bouton (0 ou 1). Ca permet d'avoir vraiment 2 couleurs radicalement differentes. 

D'ailleurs @jean-emmanuel si jamais un jour tu es chaud pour faire un petit champ CSS supplémentaire quand le bouton est ON,  je suis preneur !

**Comment by jean-emmanuel** [comment]
Yes, en effet encoder les images en base64 permettrai de les embarquer dans le json.

@Manaberry pour les toggles:
- essaye de mettre "alt-buttons" dans l'option "theme" au lancement d'o-s-c, ça donne des toggle beaucoup plus contrasté par défaut
- tu peux déjà faire du conditionnel dans l'option css:
```css
:host {
  #{
    @{this} == 1 ? "color:red;" : "color: blue;"
  }
}
```

**Comment by Manaberry** [comment]
Super ! Je test tout ca ! 

Merci

**Comment by jean-emmanuel** [comment]
Haha cool :)

J'ai un peu modifié le theme dark et ajouté un theme "flat" en voyant ce que tu avait fait. C'est dans la v0.32.5 Tu peux tester avec `theme` = `flat dark alt-buttons` sur une session sans css particulier pour voir ce que ça donne.

**Comment by Manaberry** [comment]
Ah superbe je vais tester ca dans l'heure !
J'aime beaucoup le flat "design" en general oui. Mon passif de graphiste surement ! Je ne supporte pas etre dépendant graphiquement d'un logiciel. C'est pour ca que j'adore Ableton et du coup o-s-c.
Car TouchOSC c'est trop oldschool et bridé.

**Comment by Manaberry** [comment]
Je viens de tester, c'est superbe. Ce noir clair tres legerement bleu c'est parfait pour un flat dark theme ! Facile de marier les couleurs avec une base couleur comme celle ci !

**Comment by jean-emmanuel** [comment]
Ah oui, il y a un overlay qui traine... je vais corriger le theme prochainement, en attendant tu peux mettre ça dans le css du root : 
```css
.toggle-container .toggle.on:after,
.push-container .toggle.on:after,
.switch-container .switch .value.on:after {
    background:none;
    border:1rem solid var(--color-light);
    opacity: 1;
}

.push-container .toggle.active:after {
    background: var(--color-bg);
}
```

**Comment by jean-emmanuel** [comment]
Ça devrait suffire
```css
.toggle-container .toggle.on:after,
.push-container .toggle.on:after,
.switch-container .switch .value.on:after {
    background:none;
}
```

**Comment by jean-emmanuel** [comment]
Quelques ajustements dans la v0.32.6, je n'ai pas enlevé l'overlay en question (le correctif proposé marche toujours) mais j'ai rétabli un contour qui avait sauté sur les boutons actifs.

**Comment by Manaberry** [comment]
J'ai testé, je n'ai plus le "flat" mais uniquement le dark de fonctionnel avec "flat dark" (sans utiliser alt-buttons). J'imagine que c'est voulu en attendant ?

Tu as besoin de mon json pour chopper quelques references couleurs ? (je demande on sais jamais !)

Merci pour ton boulot en tout cas, un vrai bonheur d'utiliser o-s-c

**Comment by jean-emmanuel** [comment]
Le theme "flat" change peu de choses : il enlève juste la légère surbrillance sur le bord supérieur des boutons et l'effet glass un peu 3d des widgets de la categorie "plots", il doit juste te manquer le fait d'enlever le petit dégradé des boutons en état actif, ce que le code proposé plus haut fait.

Il se pourrait bien que ces petits mods rejoignent le theme par défaut à terme, à réfléchir...

> Tu as besoin de mon json pour chopper quelques references couleurs ? (je demande on sais jamais !)

Pourquoi pas, envois donc ! (ajoute .txt à l'extension pour passer l'upload).

> Merci pour ton boulot en tout cas, un vrai bonheur d'utiliser o-s-c

Merci bien !

**Comment by Manaberry** [comment]
J'ai oublié de tester le petit bout de code forcément !

[ManaberryTemplate.txt](https://github.com/jean-emmanuel/open-stage-control/files/2127444/ManaberryTemplate.txt)

**Comment by Manaberry** [comment]
J'ai mis le petit code a la "racine" (sur le css de la tab du coup), j'ai rien vu de différent : /

**Comment by jean-emmanuel** [comment]
- dans ta session il y a déjà du css "inline" sur le tab, comme indiqué [ici](https://osc.ammd.net/extras/css-tips/), la syntaxe "inline" et la syntaxe "selecteurs" ne sont pas compatibles, voilà qui devrait fonctionner : 
```css
:host {
  letter-spacing:0;
}
.toggle-container .toggle.on:after,
.push-container .toggle.on:after,
.switch-container .switch .value.on:after {
    background:var(--color-bg);
}
```
(j'en ai profité pour ajuster le petit bout de code en plus utile visuellement)
- pour info, il y a un niveau au dessus du tab en question, le panel "root", tu peux l'editer en cliquant sur "root" dans le panneau latéral ou en faisant clic-droit>edit parent sur un ton tab principal.

**Comment by Manaberry** [comment]
Hello par ici ! 
Pour te tenir au courant, je vais update mon screen bientot (j'ai fais un truc plus propre sur les boutons avec les icons en base64). Je posterais ici quand j'aurais update, histoire que tu puisse mettre a jour sur ton site au besoin.

Bon week end !

**Comment by jean-emmanuel** [comment]
Cool, tiens moi au jus ! Comme précisé [ici](https://osc.ammd.net/widgets/widgets/#label) tu peux aussi utiliser des icônes de la police [font awesome](https://fontawesome.com/icons?d=gallery&s=solid&m=free) en précédant le nom de l'icone avec un `^`.

**Comment by Manaberry** [comment]
Génial ! Je vais tester ca.

**Comment by jean-emmanuel** [comment]
Oui, un bête erreur de ma part pistée en https://github.com/jean-emmanuel/open-stage-control/issues/343 et corrigée dans la 0.34.2 ;)

**Comment by Manaberry** [comment]
Ah pardon, j'ai pas vraiment regardé si c'était posté (mais au fond je savais que c'était déja connu haha)
Merci pour l'infos : >

**Comment by Manaberry** [comment]
Hello Jean-Emmanuel !

Dit moi, aurais tu un email sur lequel je pourrais t'envoyer un beau screenshot de mon template, avec tout le bouzin (le json etc) ? Ce serait plus pratique pour moi que de poster ici. 

Profite bien de ton été !

Manaberry

**Comment by jean-emmanuel** [comment]
Yo! Tu trouveras un mail valable dans le fichier package.json du dépôt. 
Tu peux aussi te lancer tranquillement dans git et faire un dépôt 
framagit/github pour mettre tout ça en ligne.

Merci, toi aussi !

**Comment by jean-emmanuel** [comment]
@Manaberry salut Mana, la librairie python pour le midi va changer dans la prochaine version d'open stage control pour une autre qui fonctionne quasiment à l’identique mais qui devrait être plus simple à installer pour les utilisateurs de windows car ils n'auront pas à installer le pack Visual C++. Peux tu vérifier que l'installation ne déclenche pas la procédure de compilation chez toi ? En principe cettte étape n'arrive que si aucune version précompilée n'est trouvée et cette nouvelle librairie en propose justement plus que l'ancienne pour éviter cela.
```
pip install python-rtmidi
```
Le module se présente dans python sous le même nom que l'autre, tu devras peut-être le désinstaller pour continuer d'utiliser o-s-c en attendant la sortie de la nouvelle version.
```
pip uninstall python-rtmidi
```

Merci !

**Comment by Manaberry** [comment]
Je vais tester sur mon PC principale ! Le serveur tourne sur mon ordinateur portable pour le boulot donc pas de soucis !

**Comment by jean-emmanuel** [comment]
Oui, la partie compilation pourra être nécessaire sur les systèmes plus atypiques, mais ça fait va déjà pas mal simplifier les choses. Merci beaucoup d'avoir testé !

Au fait, si jamais, il y a un maintenant forum dédié : https://openstagecontrol.discourse.group/
