### ISSUE TITLE
Startup Problems using win10 0.32.2

### ISSUE THREAD

**Issue by fluesterTIMO** [jean-emmanuel/open-stage-control#306]
I am trying to start Open-stage-control on my windows 10 machine with the prebuilt files, but the process won't start at all. I tried the 32bit and the 64bit version, but nothing is happening. Any Ideas? Thank You!

**Comment by jean-emmanuel** [comment]
Could you run the .exe from a terminal and report error messages if any ? Does it behavethe same with v0.31.0 ?

**Comment by fluesterTIMO** [comment]
from Terminal it looks like this:

fs.js:1669
      binding.lstat(baseLong);
              ^

Error: EINVAL: invalid argument, lstat 'D:\Onedrive'
    at realpathSync (fs.js:1669:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:330:24)
    at toRealPath (module.js:143:13)
    at Function.Module._findPath (module.js:192:22)
    at Function.Module._resolveFilename (module.js:483:25)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3

**Comment by jean-emmanuel** [comment]
There seem to be a compatibility issue with OneDrive, it will be fixed eventually when I upgrade o-s-c's engine to version 2 but for now there are still some bugs with it that keep me from doing so. As a workaround can you try to install the app in a different folder ?

**Comment by fluesterTIMO** [comment]
Ah, that solved the problem! Thanks.
