### ISSUE TITLE
sending preArgs give 'parseType is not defined'

### ISSUE THREAD

**Issue by gsenna** [jean-emmanuel/open-stage-control#313]
Hi,

I'm using v0.32.3 with a fader and preArgs as following: 
```
[
  { "type": "i", "value": 1 }
]

```
This used to work in v0.29.2, but now it results in:

```
A JavaScript error occurred in the main process: Uncaught Exception:
ReferenceError: parseType is not defined
    at OscServer.parseArg (/usr/lib/open-stage-control/resources/app/main/osc/index.js:81:21)
    at Object.send (/usr/lib/open-stage-control/resources/app/main/osc/index.js:219:37)
    at Object.sendOsc (/usr/lib/open-stage-control/resources/app/main/callbacks.js:207:29)
    at Socket.client.on (/usr/lib/open-stage-control/resources/app/main/server.js:48:32)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Socket.receive (/usr/lib/open-stage-control/resources/app/main/ipc/client.js:85:22)
    at WebSocket.socket.onmessage (/usr/lib/open-stage-control/resources/app/main/ipc/client.js:38:18)
    at WebSocket.onMessage (/usr/lib/open-stage-control/resources/app/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:115:13)

```

BTW, thanks for the great software!

**Comment by jean-emmanuel** [comment]
Thank you for your report, the regression has been fixed and v0.32.4 release is on the way :)
