### ISSUE TITLE
"TypeError: path must be a string or Buffer" with v41

### ISSUE THREAD

**Issue by Manaberry** [jean-emmanuel/open-stage-control#454]
Just updated to 41 to try it out. Json template is loaded but not working.
I have to downgrade until I know why I get this error.

`A JavaScript error occurred in the main process: Uncaught Exception:
TypeError: path must be a string or Buffer
at fs.lstat (fs.js:926:11)
at Object.fs.lstat (ELECTRON_ASAR.js:260:16)
at Object.sessionSetPath (C:\Program Files\Open Stage Control\resources\app\server\src\server\callbacks.js:124:1)
at Object.sessionOpened (C:\Program Files\Open Stage Control\resources\app\server\src\server\callbacks.js:113:1)
at Socket.client.on (C:\Program Files\Open Stage Control\resources\app\server\src\server\server.js:59:1)
at emitOne (events.js:115:13)
at Socket.emit (events.js:210:7)
at Socket.receive (C:\Program Files\Open Stage Control\resources\app\server\src\server\ipc\client.js:90:1)
at WebSocket.socket.onmessage (C:\Program Files\Open Stage Control\resources\app\server\src\server\ipc\client.js:43:1)
at WebSocket.onMessage (C:\Program Files\Open Stage Control\resources\app\server\node_modules\ws\lib\event-target.js:120:1)  `

**Comment by jean-emmanuel** [comment]
0.41.1 is being uploaded, it should fix it

**Comment by Manaberry** [comment]
* insert happy emoji here *

**Comment by jean-emmanuel** [comment]
:)
Does it work ?

**Comment by jean-emmanuel** [comment]
cool !
