### ISSUE TITLE
[bug] Folder up throws error

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#511]
Hi. I hit open in the editor. Hit folder up icon (folder icon with ..). Hit again and I get an error. This also happens in the file widget (I assume it's the same code). 

`
A JavaScript error occurred in the main process: Uncaught Exception:
Error: EPERM: operation not permitted, stat 'C:\found.000'
at fs.statSync (fs.js:960:11)
at Object.fs.statSync (ELECTRON_ASAR.js:279:16)
at files.filter.map (C:\Users\Luke\Desktop\OSC\open-stage-control-0.44.0-win32-x64\open-stage-control-0.44.0-win32-x64\resources\app\server\src\server\callbacks.js:405:1)
at Array.map (native)
at fs.readdir (C:\Users\Luke\Desktop\OSC\open-stage-control-0.44.0-win32-x64\open-stage-control-0.44.0-win32-x64\resources\app\server\src\server\callbacks.js:402:1)
at FSReqWrap.oncomplete (fs.js:135:15)
`

**Comment by jean-emmanuel** [comment]
Thanks for the report, fixed in git.

**Comment by jean-emmanuel** [comment]
-> v0.45.3
