### ISSUE TITLE
open-stage-control doesn't start with MIDI support

### ISSUE THREAD

**Issue by bullk** [jean-emmanuel/open-stage-control#53]
Hello,
congratulations for this fantastic work !

I'm using the open-stage-control-amd64.deb v0.17.0 with Ubuntu Studio 16.04
python-pyo installed manually since the 0.8.3 version wasn't available in distribution repositories

I'd like to use MIDI features but then it came to an issue.

```
:~$ open-stage-control --midi list
App available at http://127.0.0.1:8080 & http://192.168.1.65:8080
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'python-shell'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/share/open-stage-control/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Module.require2 (/usr/share/open-stage-control/resources/app/node_modules/vmodule/lib/require.js:12:10)
    at Module.<anonymous> (/usr/share/open-stage-control/resources/app/node_modules/radish/radish.js:130:15)
    at Module.bound [as require] (/usr/share/open-stage-control/resources/app/node_modules/lodash/dist/lodash.js:957:21)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/open-stage-control/resources/app/main/midi.js:1:98)
    at Module._compile (module.js:556:32)
```

I checked about python-shell but I only found that I can install it with npm, and don't have npm installed and don't really want to install it (with a bunch of Node dependencies) if not absolutely necessary.

So I tried to add manually python-shell module in node_modules, and it worked partially. The GUI started but remains a path issue about midi.py, then I came back to previous configuration.

Did I made something wrong ?

**Comment by jean-emmanuel** [comment]
Ahem, I'm a moron, I forgot a dependency in the package... fixed package is coming...
Thanks for your feedback !

**Comment by jean-emmanuel** [comment]
Please try [https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.1](v0.17.1)

**Comment by bullk** [comment]
Now it works. Thanks a lot !
