### ISSUE TITLE
[Bug] Buster libgconf missing

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#542]
Bonsoir,

Sous Raspbian GNU/Linux 10, je rencontre l'erreur suivante :

```
pi@raspberrypi:~/audio/open-stage-control $ npm start

> open-stage-control@0.47.1 start /home/pi/audio/open-stage-control
> electron app/

/home/pi/audio/open-stage-control/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
Une idée ? Merci

**Comment by nlebellier** [comment]
```
sudo apt install gconf2

```

**Comment by nlebellier** [comment]
bon plus de message d'erreur mais une fenêtre grise sans rien dedans

**Comment by jean-emmanuel** [comment]
Oui c'est normal, pour que la version embarquée fonctionne sous rpi il faut packager l'application avec la commande dédiée (`npm run package-rpi`).

**Comment by cyberic99** [comment]
> Oui c'est normal, pour que la version embarquée fonctionne sous rpi il faut packager l'application avec la commande dédiée (`npm run package-rpi`).

@jean-emmanuel peux-tu expliquer pourquoi et les workarounds nécessaires sur le raspberry pi?

Merci

**Comment by jean-emmanuel** [comment]
la seule différence est la version d'electron, il y a un souci de compatibilité avec les rasp sur la celle utilisée pour la version normale. À un moment donné je passerai sur une version plus récente pour réunifier tout ça mais ça (il faudra alors faire quelque chose de similaire pour la version linux-32bit qui n'est plus supportée ajourd'hui).

**Comment by nlebellier** [comment]
et une fois qu'on a packagé on fait quoi ?

**Comment by jean-emmanuel** [comment]
On lance l'executable dans `dist/open-stage-control-*/`.

**Comment by nlebellier** [comment]
ok merci pour la rapidité de la réponse :-)

`pi@raspberrypi:~/audio/open-stage-control/dist/open-stage-control-linux-armv7l $ ./open-stage-control 
`

**Comment by jean-emmanuel** [comment]
Normalement il ne devrait plus y avoir besoin de packager o-s-c avec une version spécifique pour tourner sous rpi (`npm run package` devrait suffire), si jamais tu as moyen de tester.

**Comment by nlebellier** [comment]
bonjour @jean-emmanuel 

bon voici le test avec la dernière version o-s-c sous raspbian 10. 
```
pi@raspberrypi:~/audio/open-stage-control $ ls
app           LICENSE       Procfile   resources  src
CHANGELOG.md  package.json  README.md  scripts    tests
pi@raspberrypi:~/audio/open-stage-control $ git status
Sur la branche master
Votre branche est à jour avec 'origin/master'.

rien à valider, la copie de travail est propre
pi@raspberrypi:~/audio/open-stage-control $ npm start

> open-stage-control@0.49.0-rc2 start /home/pi/audio/open-stage-control
> electron app/

sh: 1: electron: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! open-stage-control@0.49.0-rc2 start: `electron app/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the open-stage-control@0.49.0-rc2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-28T15_09_55_026Z-debug.log
```

**Comment by jean-emmanuel** [comment]
Je pense qu'il te manque un `npm install` et `npm run build` avant de pouvoir faire `npm start`

**Comment by nlebellier** [comment]
c'est pas faux :)

bon voici 
```
pi@raspberrypi:~/audio/open-stage-control $ npm start

> open-stage-control@0.49.0-rc2 start /home/pi/audio/open-stage-control
> electron app/

/home/pi/audio/open-stage-control/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/pi/audio/open-stage-control/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/pi/audio/open-stage-control/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/audio/open-stage-control/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@0.49.0-rc2 start: `electron app/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@0.49.0-rc2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-28T15_33_41_495Z-debug.log
```
je vais faire ce qui est préconisé et te tiens au courant

**Comment by nlebellier** [comment]
Même résultat 
```
pi@raspberrypi:~/audio/open-stage-control $ npm start

> open-stage-control@0.49.0-rc2 start /home/pi/audio/open-stage-control
> electron app/

/home/pi/audio/open-stage-control/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/pi/audio/open-stage-control/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/pi/audio/open-stage-control/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/audio/open-stage-control/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@0.49.0-rc2 start: `electron app/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@0.49.0-rc2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-28T15_50_46_729Z-debug.log
```
voici le log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.6
3 info using node@v13.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle open-stage-control@0.49.0-rc2~prestart: open-stage-control@0.49.0-rc2
6 info lifecycle open-stage-control@0.49.0-rc2~start: open-stage-control@0.49.0-rc2
7 verbose lifecycle open-stage-control@0.49.0-rc2~start: unsafe-perm in lifecycle true
8 verbose lifecycle open-stage-control@0.49.0-rc2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycl$
9 verbose lifecycle open-stage-control@0.49.0-rc2~start: CWD: /home/pi/audio/open-stage-control
10 silly lifecycle open-stage-control@0.49.0-rc2~start: Args: [ '-c', 'electron app/' ]
11 silly lifecycle open-stage-control@0.49.0-rc2~start: Returned: code: 1  signal: null
12 info lifecycle open-stage-control@0.49.0-rc2~start: Failed to exec start script
13 verbose stack Error: open-stage-control@0.49.0-rc2 start: `electron app/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:33$
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.j$
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid open-stage-control@0.49.0-rc2
15 verbose cwd /home/pi/audio/open-stage-control
16 verbose Linux 4.19.75-v7l+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v13.7.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 1
22 error open-stage-control@0.49.0-rc2 start: `electron app/`
22 error Exit status 1
23 error Failed at the open-stage-control@0.49.0-rc2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true 
```

**Comment by jean-emmanuel** [comment]
Tu lances bien cela dans un environnement graphique ? Tu peux auss m'envoyer la sortie du terminal après `rm -rf node_modules/` et `npm install` stp ?

**Comment by nlebellier** [comment]
téléchargeable une seule fois :-)
https://send.firefox.com/download/e0d3799e742e6bf3/#H6_6tIAKhDW9VQ71YMVMpw

**Comment by jean-emmanuel** [comment]
Merci, il y a un souci à l'installation d'electron qui ne cherche pas la bonne version, peux tu essayer `npm install --arch=armv7l electron@7.1.0` puis `npm start` ?

**Comment by nlebellier** [comment]
yes ! ça marche ! Bravo ! peut-être à ajouter quelque part dans un fichier d'install sous raspbian.

**Comment by jean-emmanuel** [comment]
Super, merci pour le test !
