### ISSUE TITLE
[Bug]  v0.47.2 Input error

### ISSUE THREAD

**Issue by iddqdosc** [jean-emmanuel/open-stage-control#546]
Hi there! Just updated to v.0.47.2 and any project that has an input widget won't open with the following error:

```
[Renderer process error]
Uncaught ReferenceError: w is not defined
at http://192.168.0.39:8080/client/open-stage-control-client.js:979:1875
(no stacktrace available) 

```
Any input widget that has a value (as simples as "1") will cause the error. How to reproduce:

Create a new project, insert input widget, add "1" as value and save to cause the error.

Here's the error from the "Ardour" example project:
```

[Renderer process error]
Uncaught ReferenceError: w is not defined
at flush (src/client/app/managers/state.js:216:29)
at pushValueNewProp (src/client/app/managers/state.js:201:41)
at widget.getProp (src/client/app/parser.js:97:25)
at Array(this.getProp (src/client/app/widgets/containers/panel.js:104:27)
at Panel.defaults()._props (src/client/app/widgets/containers/strip.js:48:8)
at this.getIterator (src/client/app/parser.js:78:21)
at Array(this.getProp (src/client/app/widgets/containers/panel.js:104:27)
at Panel.defaults()._props (src/client/app/widgets/containers/strip.js:48:8)
at this.getIterator (src/client/app/parser.js:78:21)
at Array(this.getProp (src/client/app/widgets/containers/panel.js:104:27)

PARSING ERROR. w is not defined.

```

And here's another error from one of my projects:

```

[Renderer process error]
Uncaught ReferenceError: w is not defined
at flush (src/client/app/managers/state.js:216:29)
at pushValueNewProp (src/client/app/managers/state.js:201:41)
at widget.getProp (src/client/app/parser.js:97:25)
at Array(this.getProp (src/client/app/widgets/containers/panel.js:104:27)
at constructor (src/client/app/widgets/containers/modal.js:47:8)
at this.getIterator (src/client/app/parser.js:78:21)
at Array(this.getProp (src/client/app/widgets/containers/panel.js:104:27)
at constructor (src/client/app/widgets/containers/tab.js:30:8)
at this.getIterator (src/client/app/parser.js:78:21)
at Array(this.getProp (src/client/app/widgets/containers/panel.js:68:27)

PARSING ERROR. w is not defined.

```
Rolling back to v.0.47.1 works again.

Cheers!

**Comment by jean-emmanuel** [comment]
Thanks for reporting, hotfixed v0.47.3 is being uploaded !

**Comment by iddqdosc** [comment]
Thanks for the hotfix, Jean. No more input errors. Cheers!
