### ISSUE TITLE
[Bug] Parsing error when opening a .json file

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#556]
Hi

I realized I reported an issue on the discourse (https://openstagecontrol.discourse.group/t/parsing-error-when-opening-a-file/208), maybe here is a better place:

- Open Stage Control version: b285e9109fd4d29b113fef68d85cdf9acc67f7e3
- Operating system: linux debian 8
- Client type: electron

I have a json file that I saved in o-s-c, that produces a parsing error when I try to open it.
I tried to simplify it it while still keeping the parsing error.

The error is due to line 242.

I know that I am using values in a matrix, and that these values could be uninitialized on loading.

I already enclosed the calculations in a try/catch block, but node still crashes.

What would the correct way to prevent the crash?

thx

The error:

App available at http://…

[Renderer process error]
Uncaught NotFoundError: Failed to execute ‘replaceChild’ on ‘Node’: The node to be replaced is not a child of this node.
at updateWidget (src/client/app/editor/data-workers.js:106:35)
at reCreateWidget (src/client/app/widgets/common/widget.js:927:15)
at changedProps.push (src/client/app/widgets/common/widget.js:709:24)
at this.updateLinkedPropsWithNesting (src/client/app/widgets/common/widget.js:381:17)
at linkedValueChangedCallback (src/client/app/widgets/common/widget.js:346:21)
at this._listeners[evt].slice (src/client/app/events/event-emitter.js:29:29)
at listeners[i] (src/client/app/events/event-emitter.js:35:41)
at listeners[i] (src/client/app/events/event-emitter.js:35:41)
at listeners[i] (src/client/app/events/event-emitter.js:35:41)
at changed (src/client/app/widgets/common/widget.js:220:13)

[crashing.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/3563963/crashing.json.zip)

**Comment by jean-emmanuel** [comment]
J'ai mis en ligne un correctif qui empêche le problème d'arriver. On est là sur un cas assez épineux qui demandera peut-être un changement plus profond à l'avenir pour être mieux traité.

**Comment by cyberic99** [comment]
Thanks for you fix @jean-emmanuel.

However, I still get errors when using some /EDIT commands.

Would it be possible to catch these errors and print the widget which caused them?

It would help me (and others) to pinpoint problems more easily

Thanks

**Comment by jean-emmanuel** [comment]
I've tracked the issue to something deeper than a widget issue, it might take some time to get fixed.

**Comment by cyberic99** [comment]
I can also trigger error like these:
```
[Renderer process error]
Uncaught NotFoundError: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at updateWidget (src/client/app/editor/data-workers.js:106:35)
    at widgetManager.getWidgetById (src/client/app/remote-control.js:27:12)
    at exec (src/client/app/remote-control.js:239:28)
    at receive (src/client/app/osc.js:38:72)
    at receiveOsc (src/client/app/ipc/callbacks.js:25:12)
    at require (src/client/app/ipc/index.js:57:16)
    at this._listeners[evt].slice (src/client/app/events/event-emitter.js:29:29)
    at Array.isArray (src/client/app/ipc/index.js:140:21)
    at onmessage (src/client/app/ipc/index.js:91:21)
```

**Comment by cyberic99** [comment]
> I've tracked the issue to something deeper than a widget issue, it might take some time to get fixed.

allright. Maybe my /EDITs are a bit too rough... ?

**Comment by cyberic99** [comment]
If I can help in any way or if you want some repro cases, tell me

**Comment by jean-emmanuel** [comment]
I found and fixed the bug, can you try the patch ?

**Comment by cyberic99** [comment]
I tried the latest git and I don't have the error anymore.

However, something (else?) is definitely broken.
My dashboard matrices are all empty.

With this session file:

[idx.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/3575113/idx.json.zip)

at commit 54403a7db80487bf1154d3699025c7a1f2218ab4:

![image](https://user-images.githubusercontent.com/193917/64266868-a336ba80-cf35-11e9-8346-d0bdef6afcac.png)

at commit 34d740b2d98c4903da59c91e58c3f1e5e889852f:

![image](https://user-images.githubusercontent.com/193917/64267008-e8f38300-cf35-11e9-9eef-ba3763dae69e.png)

It seems that arrays start at ``1`` now, instead of ``0`` before?

Maybe it is because of the deps bump that happened a few commits ago?

the widget in the session just contains this in ``value``:
```
#{
[1,2][0]
}
```

Sorry, I have no time right now to see search exactly when the behaviour changed...

**Comment by jean-emmanuel** [comment]
Hmm, it's very likely to be cause indeed !

**Comment by jean-emmanuel** [comment]
I have downgraded mathjs to prevent this.

**Comment by cyberic99** [comment]
Wow that was a big breaking change!
I failed to find any mention of it in the changelog

I'll retest with your last commit, soon

**Comment by jean-emmanuel** [comment]
It wasn't documented because it was a bug ;).

**Comment by cyberic99** [comment]
> It wasn't documented because it was a bug ;).

you mean, a bug in ``mathjs`` ?

**Comment by jean-emmanuel** [comment]
No, a bug in o-s-c caused by upgrading mathjs. The root cause however is that mathjs somehow changed the way matrix/array indexing are configured.

**Comment by cyberic99** [comment]
OK.

Back to the issue, the error I got has disappeared now, everything is working smoothly, thanks!

I'll do more tests and keep you updated if I find something. 

Thanks!
(and I'll add 1 or 2 feature requests ;-))
