### ISSUE TITLE
[Bug] fader / steps : typing a number freezes editor

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#635]
create a fader
in 'steps' : type in any number : 
console says :

(ERROR, CLIENT) Uncaught RangeError: Invalid array length
    at this.getProp (src/client/widgets/sliders/slider.js:220:20)
    at super.onPropChanged (src/client/widgets/sliders/slider.js:233:21)
    at this.checkLinkedProps (src/client/widgets/common/widget.js:756:21)
    at propNames.some (src/client/editor/data-workers.js:25:32)
    at this.inspector.on('update', (src/client/editor/index.js:38:32)
    at this._listeners[evt].slice (src/client/events/event-emitter.js:29:29)
    at v.replace (src/client/ui/ui-inspector.js:224:13)
    at dispatchEvent (src/client/dom.js:32:16)
    at onKeydown (src/client/ui/ui-inspector.js:238:16)

Then the fader cannot be used, and return key stops working everywhere in the editor.

- Open Stage Control version1.0.0-beta9
- Operating system : windows10

**Comment by jean-emmanuel** [comment]
I could only reproduce the error by typing a decimal number, and it doesn't break the editor anymore (as of 669b8cfd1af3f0bb6274af18dcd60b43c7d5b95b)

**Comment by jean-emmanuel** [comment]
Included in beta 10
