### ISSUE TITLE
[Bug] range : default = array causes (ERROR, CLIENT) Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#660]
si on essaye de définir la valeur par default d'un range avec un array 
par ex [0.4, 0.6]
et que je sauve la session, en essayant de l'ouvrir à nouveau, j'ai ce message d'erreur : 

```
(ERROR, CLIENT) Uncaught TypeError: Cannot read property '0' of undefined
    at setValue (src/client/widgets/sliders/range.js:176:20)
    at new Slider (src/client/widgets/sliders/slider.js:77:13)
    at constructor (src/client/widgets/sliders/fader.js:59:8)
    at constructor (src/client/widgets/sliders/range.js:19:8)
    at this.getIterator (src/client/parser.js:76:21)
    at Array(this.getProp (src/client/widgets/containers/panel.js:149:27)
    at StaticProperties (src/client/widgets/mixins/static_properties.js:1:46)
    at constructor (src/client/widgets/containers/root.js:39:8)
    at this.getIterator (src/client/parser.js:76:21)
    at load (src/client/managers/session/index.js:45:23)
```

**et l'éditeur ne répond plus.**

d'autre part, (avant de fermer ma session corrompue), si je met doubleTap : true pour qu'un double-click reset le range sur ses valeurs par default, ça fait un comportement un peu étrange : le premier double click reset la valeur basse, puis le second double-click reset la valeur haute...
ça me semblerait plus logique qu'un seul double-click reset les 2 valeurs d'un coup, isn't it ?

_heureusement qu'un json est facile à éditer, j'ai pu facilement corriger les valeurs de "default" et retrouver ma session :-)
(mais j'ai quand même eu quelques sueurs froides !)_

**Comment by jean-emmanuel** [comment]
merci pour le rapport, je corrige ça bientô

**Comment by jean-emmanuel** [comment]
fixed in sources
