### ISSUE TITLE
[Bug] Error Install from sources on raspberry pi OS

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#677]
Bonjour Jean-Emmanuel,

```
pi@raspberrypi:~/audio $ git clone https://github.com/jean-emmanuel/open-stage-control.git
Clonage dans 'open-stage-control'...
remote: Enumerating objects: 222, done.
remote: Counting objects: 100% (222/222), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 45647 (delta 131), reused 134 (delta 68), pack-reused 45425
Réception d'objets: 100% (45647/45647), 16.34 MiB | 1.91 MiB/s, fait.
Résolution des deltas: 100% (26895/26895), fait.
pi@raspberrypi:~/audio $ npm --version
7.0.15
pi@raspberrypi:~/audio $ node --version
v15.4.0
pi@raspberrypi:~/audio $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a020d3
Serial		: 00000000aeb2e6c2
Model		: Raspberry Pi 3 Model B Plus Rev 1.3
pi@raspberrypi:~/audio $ cd open-stage-control/
pi@raspberrypi:~/audio/open-stage-control $ npm install --arch=armv7l
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: Please update to v 2.2.x
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated sortablejs@1.10.2: Object.assign was not transformed during the build of sortablejs, so it won't work in browsers where this does not exist (for example IE11). Please downgrade your version to 1.10.2 to keep supporting <=IE11 or upgrade to >2.0 where IE will no longer be supported.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

pi@raspberrypi:~/audio/open-stage-control $ npm install --arch=armv7l

> open-stage-control@1.8.1 postinstall
> echo '\033[36m=> Dependencies installed successfully. Run "npm run build" to build the assets.\033[0m
> '

=> Dependencies installed successfully. Run "npm run build" to build the assets.


up to date, audited 1131 packages in 24s

77 packages are looking for funding
  run `npm fund` for details

2 low severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
pi@raspberrypi:~/audio/open-stage-control $ npm run build

> open-stage-control@1.8.1 build
> npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
> '


> open-stage-control@1.8.1 build-css
> node scripts/build-css.js

/home/pi/audio/open-stage-control/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 15.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v5.0.0
    at module.exports (/home/pi/audio/open-stage-control/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/pi/audio/open-stage-control/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/pi/audio/open-stage-control/scripts/build-css.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR! code 1
npm ERR! path /home/pi/audio/open-stage-control
npm ERR! command failed
npm ERR! command sh -c node scripts/build-css.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-12-19T12_12_22_870Z-debug.log
npm ERR! code 1
npm ERR! path /home/pi/audio/open-stage-control
npm ERR! command failedSeems to h
npm ERR! command sh -c npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
npm ERR! command '

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-12-19T12_12_22_969Z-debug.log
```
A priori un problème avec node-sass et node.js version 15

**Comment by nlebellier** [comment]
Downgrade to node 12 to install and it works.
