### ISSUE TITLE
Erreur en modifiant le range 

### ISSUE THREAD

**Issue by CtrlZ-Music** [jean-emmanuel/open-stage-control#743]
Error while setting range to: "{\n \"min\": #{@{knob_reverbgeneral_earlymin}+0.1},\n \"max\": 120\n}".
It's probably a bug, please open a new bug ticket with the followigin informations athttps://github.com/jean-emmanuel/open-stage-control/issues
Uncaught TypeError: Cannot convert undefined or null to object
at this.getProp (src/client/widgets/sliders/slider.js:29:52)
at constructor (src/client/widgets/sliders/knob.js:58:8)
at this.getIterator (src/client/parser.js:77:21)
at w.scroll (src/client/editor/data-workers.js:104:27)
at this.inspector.on('update', (src/client/editor/index.js:48:36)
at this._listeners[evt].slice (src/client/events/event-emitter.js:29:29)
at JSON.parseFlex (src/client/ui/ui-inspector.js:214:13)
at dispatchEvent (src/client/dom.js:32:16)
at onKeydown (src/client/ui/ui-inspector.js:231:20)

**Comment by jean-emmanuel** [comment]
Fixed in v1.9.12
