### ISSUE TITLE
[Bug] html in modal leads to error

### ISSUE THREAD

**Issue by UdoHo** [jean-emmanuel/open-stage-control#749]
Using the html field in a modal always leads to an error, even in the simplest possible session. 

launcher:

(ERROR, CLIENT) Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted i
[modal-html-test.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7079314/modal-html-test.json.txt)
s not a child of this node.
    at morph (src/client/widgets/common/widget.js:1135:27)

client:

Error while setting html to: "test".
It's probably a bug, please open a new bug ticket with the followigin informations athttps://github.com/jean-emmanuel/open-stage-control/issues
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
at morph (src/client/widgets/common/widget.js:1135:27)
at Modal.onPropChanged (src/client/widgets/common/widget.js:900:21)
at onPropChanged (src/client/widgets/containers/panel.js:283:18)
at onPropChanged (src/client/widgets/containers/modal.js:245:18)
at this.reCreateWidget (src/client/widgets/common/widget.js:847:21)
at propNames.some (src/client/editor/data-workers.js:26:32)
at this.inspector.on('update', (src/client/editor/index.js:48:36)
at this._listeners[evt].slice (src/client/events/event-emitter.js:29:29)
at JSON.parseFlex (src/client/ui/ui-inspector.js:214:13)
at dispatchEvent (src/client/dom.js:32:16)

OS:  Ubuntu based Linux

**Comment by jean-emmanuel** [comment]
Thanks for the report, I'll probably remove the html property for this widget.

**Comment by jean-emmanuel** [comment]
Done in v1.9.14
