### ISSUE TITLE
[Bug] using node to launch o-s-c

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#772]
hi,

i'm trying to run o-s-c with node as mentioned into the doc (https://openstagecontrol.ammd.net/docs/getting-started/running-with-node/#running-with-node)

Linux manjaro-pi 5.10.92-1-MANJARO-ARM-RPI #1 SMP PREEMPT Mon Jan 17 14:03:48 CST 2022 aarch64 GNU/Linux

```

[nlb@manjaro-pi open-stage-control]$ git log
commit 1c69c029dc171c520396988221e48444ee96a64f (HEAD -> master, origin/master, origin/HEAD)
Author: jean-emmanuel <jean-emmanuel.doucet@groolot.net>
Date:   Mon Jan 31 09:49:17 2022 +0100

    clean

commit f28326c882cbe3809f2fe57e4d7972da2780bddd
Author: jean-emmanuel <jean-emmanuel.doucet@groolo<!--


Date:   Mon Jan 31 09:08:41 2022 +0100

    inspector: modularize code editor a bit

commit 01f1c630fd3b2e70e531dfbcd26ff5f905c5fea0
Author: jean-emmanuel <jean-emmanuel.doucet@groolot.net>
Date:   Sun Jan 30 17:16:00 2022 +0100

    inspector: code editor: prevent issue on middle click

commit f42900058d8d9d38475645cd65aaaf1ae849cc67
Author: jean-emmanuel <jean-emmanuel.doucet@groolot.net>
Date:   Sun Jan 30 17:08:14 2022 +0100

[nlb@manjaro-pi open-stage-control]$ node -v
v16.13.2
[nlb@manjaro-pi open-stage-control]$ node ./app/
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './server/open-stage-control-server'
Require stack:
- /home/nlb/open-stage-control/app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/nlb/open-stage-control/app/index.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/nlb/open-stage-control/app/index.js' ]
}
[nlb@manjaro-pi open-stage-control]$ 

```

any idea ?

**Comment by jean-emmanuel** [comment]
`npm run build` ?

**Comment by nlebellier** [comment]
nope...

```
[nlb@manjaro-pi open-stage-control]$ node -v
v14.18.3
[nlb@manjaro-pi open-stage-control]$ npm -v
6.14.15
[nlb@manjaro-pi open-stage-control]$ npn run build
bash: npn : commande introuvable
[nlb@manjaro-pi open-stage-control]$ npm run build

> open-stage-control@1.14.3 build /home/nlb/open-stage-control
> npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
'


> open-stage-control@1.14.3 build-css /home/nlb/open-stage-control
> node scripts/build-css.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node-sass'
Require stack:
- /home/nlb/open-stage-control/scripts/build-css.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/nlb/open-stage-control/scripts/build-css.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/nlb/open-stage-control/scripts/build-css.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@1.14.3 build-css: `node scripts/build-css.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@1.14.3 build-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nlb/.npm/_logs/2022-02-01T15_39_21_500Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@1.14.3 build: `npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
npm ERR! '`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@1.14.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nlb/.npm/_logs/2022-02-01T15_39_21_623Z-debug.log
[nlb@manjaro-pi open-stage-control]$ 
```

**Comment by jean-emmanuel** [comment]
Either use the prebuilt node version  available on the website or use an older node version to build o-s-c (https://github.com/jean-emmanuel/open-stage-control/issues/753).

**Comment by nlebellier** [comment]
the prebuild node version works :+1:  but how can have the debug server windows ?
```
[nlb@manjaro-pi open-stage-control]$ node -v
v14.18.3
[nlb@manjaro-pi open-stage-control]$ npm -v
6.14.15
[nlb@manjaro-pi open-stage-control]$ npn run build
bash: npn : commande introuvable
[nlb@manjaro-pi open-stage-control]$ npm run build

> open-stage-control@1.14.3 build /home/nlb/open-stage-control
> npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
'


> open-stage-control@1.14.3 build-css /home/nlb/open-stage-control
> node scripts/build-css.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node-sass'
Require stack:
- /home/nlb/open-stage-control/scripts/build-css.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/nlb/open-stage-control/scripts/build-css.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/nlb/open-stage-control/scripts/build-css.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@1.14.3 build-css: `node scripts/build-css.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@1.14.3 build-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nlb/.npm/_logs/2022-02-01T15_39_21_500Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@1.14.3 build: `npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
npm ERR! '`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@1.14.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nlb/.npm/_logs/2022-02-01T15_39_21_623Z-debug.log
[nlb@manjaro-pi open-stage-control]$ 
```

i have tried the older version of npm to build and it failed.


your package.json says ``6.0.1`` 

```
NodeJS | Supported node-sass version | Node Module
-- | -- | --
Node 17 | 7.0+ | 102
Node 16 | 6.0+ | 93
```



```
[nlb@manjaro-pi open-stage-control]$ nvm use 16.*
Now using node v16.13.2 (npm v8.1.2)
[nlb@manjaro-pi open-stage-control]$ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.4.0
npm notice Run npm install -g npm@8.4.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /home/nlb/open-stage-control/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /home/nlb/.nvm/versions/node/v16.13.2/bin/node /home/nlb/open-stage-control/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/nlb/.nvm/versions/node/v16.13.2/bin/node',
npm ERR! gyp verb cli   '/home/nlb/open-stage-control/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.2 | linux | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.10.1"
npm ERR! gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.2
npm ERR! gyp verb command install [ '16.13.2' ]
npm ERR! gyp verb install input version string "16.13.2"
npm ERR! gyp verb install installing version: 16.13.2
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.2
npm ERR! gyp verb build dir attempting to create "build" dir: /home/nlb/open-stage-control/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/nlb/open-stage-control/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/nlb/open-stage-control/node_modules/node-sass/build/config.gypi
npm ERR! (node:19051) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /home/nlb/open-stage-control/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/nlb/open-stage-control/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/nlb/open-stage-control/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/nlb/open-stage-control/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/nlb/open-stage-control/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/nlb/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/nlb/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/nlb/open-stage-control/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/nlb/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/nlb/open-stage-control/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture arm64
npm ERR! gyp verb node dev dir /home/nlb/.cache/node-gyp/16.13.2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/nlb/open-stage-control/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/nlb/open-stage-control/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/nlb/open-stage-control/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.10.92-1-MANJARO-ARM-RPI
npm ERR! gyp ERR! command "/home/nlb/.nvm/versions/node/v16.13.2/bin/node" "/home/nlb/open-stage-control/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/nlb/open-stage-control/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nlb/.npm/_logs/2022-02-01T15_57_19_962Z-debug.log
```

Que se passe-t'il ?

**Comment by nlebellier** [comment]
i tried believe me :-)

```
[nlb@manjaro-pi open-stage-control]$ nvm install v15.*
Downloading and installing node v15.14.0...
od: ../lib/systemd/systemd: Aucun fichier ou dossier de ce type
Downloading https://nodejs.org/dist/v15.14.0/node-v15.14.0-linux-arm64.tar.xz...
############################################################################################################# 100,0%
Computing checksum with sha256sum
Checksums matched!
Now using node v15.14.0 (npm v7.7.6)
[nlb@manjaro-pi open-stage-control]$ rm -rf node_modules/
[nlb@manjaro-pi open-stage-control]$ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /home/nlb/open-stage-control/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /home/nlb/.nvm/versions/node/v15.14.0/bin/node /home/nlb/open-stage-control/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/nlb/.nvm/versions/node/v15.14.0/bin/node',
npm ERR! gyp verb cli   '/home/nlb/open-stage-control/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | linux | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.10.1"
npm ERR! gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 15.14.0
npm ERR! gyp verb command install [ '15.14.0' ]
npm ERR! gyp verb install input version string "15.14.0"
npm ERR! gyp verb install installing version: 15.14.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 15.14.0
npm ERR! gyp verb build dir attempting to create "build" dir: /home/nlb/open-stage-control/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/nlb/open-stage-control/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/nlb/open-stage-control/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /home/nlb/open-stage-control/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/nlb/open-stage-control/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/nlb/open-stage-control/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/nlb/open-stage-control/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/nlb/open-stage-control/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/nlb/.cache/node-gyp/15.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/nlb/.cache/node-gyp/15.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/nlb/open-stage-control/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/nlb/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/nlb/open-stage-control/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture arm64
npm ERR! gyp verb node dev dir /home/nlb/.cache/node-gyp/15.14.0
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/nlb/open-stage-control/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/nlb/open-stage-control/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/nlb/open-stage-control/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/nlb/open-stage-control/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.10.92-1-MANJARO-ARM-RPI
npm ERR! gyp ERR! command "/home/nlb/.nvm/versions/node/v15.14.0/bin/node" "/home/nlb/open-stage-control/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/nlb/open-stage-control/node_modules/node-sass
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nlb/.npm/_logs/2022-02-01T16_59_16_981Z-debug.log
[nlb@manjaro-pi open-stage-control]$ npm run build

> open-stage-control@1.14.3 build
> npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
> '


> open-stage-control@1.14.3 build-css
> node scripts/build-css.js

node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'node-sass'
Require stack:
- /home/nlb/open-stage-control/scripts/build-css.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/nlb/open-stage-control/scripts/build-css.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/nlb/open-stage-control/scripts/build-css.js' ]
}
[nlb@manjaro-pi open-stage-control]$ 
```

voilà voilà

**Comment by jean-emmanuel** [comment]
node-sass doesn't provide prebuilt binaries for your system, you'll need to install some build tools (`make` at least) to make the install process work. Reading the errors in the logs is very important to do this, here the relevant error was `Error: not found: make`, but there will probably be others along the way as there often is when building softwares from sources. Again, I recommend using the prebuilt node package which will work just fine (using a build from the master branch is not to be considered safe).

> the prebuild node version works +1 but how can have the debug server windows ?

There's no launcher window in headless mode, debug logs are printed in the terminal directly.

**Comment by nlebellier** [comment]
> There's no launcher window in headless mode, debug logs are printed in the terminal directly.

ok is there a way to list the midi devices into the terminal ?

**Comment by alin89c** [comment]
Have you tried...
`node /path/to/o-s-c/node/folder --midi list`
?

**Comment by nlebellier** [comment]
thanks ! this is the good command ! i need to install python-rtmidi of course.

**Comment by nlebellier** [comment]
hi there,

just to add that with these commands
```
sudo pacman -Sy base-devel
 sudo pacman -Sy python-devtools
 sudo pacman -S cmake gcc python3
 pip install python-rtmidi
```
o-s-c works perfectly on manjaro.

and i am able to build not only the node-version from the github repo.
Au plaisir !
