### ISSUE TITLE
[Bug] config.json pas trouvé

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#839]
Bonjour bonsoir,

Sur un Windows 10 avec installation depuis le .exe, version 1.25.7

```
(ERROR) Could not read config from file:C:\Users\nlb\AppData\Roaming\open-stage-control\Config\config.json
Error: ENOENT: no such file or directory, open 'C:\Users\nlb\AppData\Roaming\open-stage-control\Config\config.json'
    at Object.openSync (node:fs:582:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.readFileSync (node:fs:450:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9148)
    at Object.358.../../package.json (D:\audio\open-stage-control_1.25.7_win32-x64\resources\app\server\src\server\settings.js:117:1)
    at o (D:\audio\open-stage-control_1.25.7_win32-x64\resources\app\server\node_modules\browser-pack\_prelude.js:1:1)
    at D:\audio\open-stage-control_1.25.7_win32-x64\resources\app\server\node_modules\browser-pack\_prelude.js:1:1
    at Object.348../callbacks (D:\audio\open-stage-control_1.25.7_win32-x64\resources\app\server\src\server\index.js:4:1)
    at o (D:\audio\open-stage-control_1.25.7_win32-x64\resources\app\server\node_modules\browser-pack\_prelude.js:1:1)
    at r (D:\audio\open-stage-control_1.25.7_win32-x64\resources\app\server\node_modules\browser-pack\_prelude.js:1:1) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\nlb\\AppData\\Roaming\\open-stage-control\\Config\\config.json'
}
(INFO) Server started, app available at 
    http://192.168.1.28:8080
    http://127.0.0.1:8080
```

Effectivement

![image](https://github.com/jean-emmanuel/open-stage-control/assets/4880966/20a9c124-7009-4a23-a71c-4b8774645d18)

Reste à disposition pour tout renseignement complémentaire.

**Comment by nlebellier** [comment]
Deuxième lancement : le config.json est créée et supprime le message d'erreur.

Bon curieux non ?

**Comment by jean-emmanuel** [comment]
Il y avait un souci de logique dans la création de ce fichier, c'est maintenant corrigé.
